###Tom Quinn

###variables
@url = http://localhost:3020/api/v1

@id = 692e503fba7443a084616da5

### get all events
GET {{url}}/events

### get event by eventID
GET {{url}}/events/{{id}}

### get event by eventID if eventID is not found
GET {{url}}/events/6



###get all menu items
GET {{url}}/menu

### test /menu-item/:number if number is found
GET {{url}}/menu/5

### test /menu-item/:number if number is not found
GET {{url}}/menu/7

###  add a new menu item
POST {{url}}/menu/add
Content-Type: application/json

{
    "number": 6,
    "description": "A delicious vegan burger with lettuce, tomato, and our special sauce.",
    "name": "Vegan Burger",
    "price": 8.99,
    "image": ""
}


###  add a new menu item
POST {{url}}/events/add
Content-Type: application/json

{    
    "name": "Open Air",
    "location": "Maywood Park, 187 W Diversy St, Chicago, IL 60007",
    "date": "2025-07-31",
    "time": "8:00 AM - 11:59 PM"
}
