###variables
@url = http://localhost:3000

### test get all events
GET {{url}}/api/v1/events

### test get event by eventID
GET {{url}}/api/v1/events/1

###test get event by eventID if eventID is not found
GET {{url}}/api/v1/events/99



###get all menu items
GET {{url}}/api/v1/menu

### test /menu-item/:number if number is found
GET {{url}}/api/v1/menu/5

### test /menu-item/:number if number is not found
GET {{url}}/api/v1/menu/6



